// lib/panama-regions.ts

export const provinciasDistritos: Record<string, string[]> = {
	'Bocas del Toro': [
		'Bocas del Toro',
		'Changuinola',
		'Chiriquí Grande',
		'Almirante',
		'Isla Colón',
	],
	Coclé: ['Aguadulce', 'Antón', 'La Pintada', 'Natá', 'Olá', 'Penonomé'],
	Colón: ['Colón', 'Chagres', 'Donoso', 'Portobelo', 'Santa Isabel'],
	Chiriquí: [
		'David',
		'Alanje',
		'Barú',
		'Boquerón',
		'Boquete',
		'Bugaba',
		'Dolega',
		'Gualaca',
		'Remedios',
		'Renacimiento',
		'San Félix',
		'San Lorenzo',
		'Tierras Altas',
		'Volcán',
	],
	Darién: ['Chepigana', 'Pinogana', 'Santa Fe'],
	Herrera: [
		'Chitré',
		'Las Minas',
		'Los Pozos',
		'Ocú',
		'Parita',
		'Pesé',
		'Santa María',
	],
	'Los Santos': [
		'Guararé',
		'Las Tablas',
		'Los Santos',
		'Macaracas',
		'Pedasí',
		'Pocrí',
		'Tonosí',
	],
	Panamá: [
		'Ciudad de Panamá',
		'San Miguelito',
		'Chepo',
		'Chilibre',
		'Pacora',
		'24 de Diciembre',
		'Tocumen',
		'Las Cumbres',
		'Pedregal',
		'Parque Lefevre',
		'Juan Díaz',
		'Ancón',
		'Bethania',
		'Bella Vista',
		'El Chorrillo',
		'Curundú',
		'Santa Ana',
		'San Francisco',
		'Río Abajo',
		'Calidonia',
		'Pueblo Nuevo',
		'Las Mañanitas',
		'Ernesto Córdoba Campos',
	],
	'Panamá Oeste': ['La Chorrera', 'Arraiján', 'Capira', 'Chame', 'San Carlos'],
	Veraguas: [
		'Atalaya',
		'Calobre',
		'Cañazas',
		'La Mesa',
		'Las Palmas',
		'Montijo',
		'Río de Jesús',
		'San Francisco',
		'Santa Fe',
		'Santiago',
		'Soná',
	],
	'C. Ngäbe-Buglé': [
		'Kankintú',
		'Kusapín',
		'Müna',
		'Nole Duima',
		'Ñürüm',
		'Besikó',
		'Mironó',
		'Jirondai',
		'Santa Catalina o Calovébora',
	],
};

export const provincias = Object.keys(provinciasDistritos);
